Added code for week-2 assignments both assignment-1 and assignment-2
Kavya-Gowtham/p4-tanish-Kavya-Gowtham pull request #1
Opened 2022-07-30 11:39 UTC by Kavya-Gowtham

2022-07-30 19:26 UTC, TanishShah37 requested changes
CSS can reused here, .Improve Folder Structure for CSS files. Psuedo Selectors can be used like is and where

2022-07-30 19:26 UTC, TanishShah37 commented on Week-2/Assignment-2.2/style.css
> +
CSS can reused here,

2022-07-31 09:51 UTC, Kavya-Gowtham commented on Week-2/Assignment-2.2/style.css
> +
Changes are updated please review.

2022-07-31 09:52 UTC, TanishShah37 approved these changes

2022-07-31 09:54 UTC, merged